### ISSUE TITLE
Storage Handling pre-1.19.4

### ISSUE THREAD

**Issue by WillowMist** [SirEdvin/Peripheralium#6]
Is there any way to implement storage handling in a similar way to 1.19.4 in 1.19 (Which I assume is still 1.19.2 compatible)?  It appears that the API looks much more usable for item_storage peripherals.   Or are there parts that are only possible with the newer versions of minecraft?

I'm happy to try to hack it in myself, but I wanted to ask first.   My end goal is to be able to add the Create Item Vault to an ARTIST storage network, but with api calls that are all different from Inventory API calls, I'm not sure I could handle it.

Thanks

**Comment by SirEdvin** [comment]
Do you mean partially provide slotted storages support for fabric, so it at least try to provide `inventory` peripheral when this possible?
It should be possible, I will take a look into backporting this

**Comment by WillowMist** [comment]
I'd just like to be able to access 'size' and use push and pull methods with the plural of 'item'...  Well, basically, I was just hoping the inventory api methods would work.  i can probably make evertything work if I can just get a 'size' method, but not having to map the methods would be cool too. :)

**Comment by WillowMist** [comment]
Looking closer, I see that size in Inventory is a number of slots.  So yeah, there may not be a perfect way to make that happen.  However, if it  could still be an item_storage type, then maybe size is just the total capacity either directly, or divided by 64 if it tracks size by the largest POSSIBLE number of items that could be contained.  I guess as long as SOME kind of number can be gleaned from it, I can make it work.  But if you see a way to backport your newer methods into 1.19.2, I'm sure I could work with that, too :)

**Comment by SirEdvin** [comment]
So ... thanks to Fabric this is not possible to implement in way that I want this to do. SlottedStorage exists only in newer fabric versions and without this there is no actual interface to be able to understand size of storage.

I probably can try to add some special create integration in UnlimitedPeripheralWorks in 1.18/1.19, but this issue can't be resolved.
